### ISSUE TITLE
Need to add more checking with 'noma start'

### ISSUE THREAD

**Issue by nolim1t** [lncm/noma#35]
## System
Alpine Linux x86_64 3.10

## Reproducing

1. Clone noma repo (master currently at 855d5d7031e05e28c6e1fca7c5ab9484f839c01c)
2. run ```python3 setup.py bdist_wheel```
3. run ```pip3 install dist/noma-*-py3-none-any.whl```
4. run ```noma start```

***Output***

```
Note: using compose from pi-factory repo
Cloning into 'pi-factory'...
remote: Enumerating objects: 182, done.
remote: Counting objects: 100% (182/182), done.
remote: Compressing objects: 100% (80/80), done.
remote: Total 4239 (delta 84), reused 152 (delta 68), pack-reused 4057
Receiving objects: 100% (4239/4239), 3.55 MiB | 618.00 KiB/s, done.
Resolving deltas: 100% (2393/2393), done.
Traceback (most recent call last):
  File "/usr/bin/noma", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python3.7/site-packages/noma/noma.py", line 296, in main
    node(args)
  File "/usr/lib/python3.7/site-packages/noma/noma.py", line 188, in node
    node.start()
  File "/usr/lib/python3.7/site-packages/noma/node.py", line 66, in start
    os.chdir(COMPOSE_PATH)
FileNotFoundError: [Errno 2] No such file or directory: '/media/noma/compose/neutrino'
```

**Comment by AnotherDroog** [comment]
`noma start` now checks filesystem structure and config
