### ISSUE TITLE
ContextualVersionConflict exception on first run

### ISSUE THREAD

**Issue by ln2max** [lncm/noma#67]
After installing `noma` on a clean Debian box:
```
$ sudo noma start
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 655, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 963, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 854, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (requests 2.12.4 (/usr/lib/python3/dist-packages), Requirement.parse('requests<3,>=2.20.0'), {'docker-compose'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/noma", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3019, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3032, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 657, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 670, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 854, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (requests 2.12.4 (/usr/lib/python3/dist-packages), Requirement.parse('requests<3,>=2.20.0'), {'docker-compose'})
```

**Comment by ln2max** [comment]
` pip3 install noma requests==2.2.0` didn't work. Looks like an issue with the docker-compose install, maybe because I was messing around with docker-compose. Trying everything again on a re-imaged *clean* clean install.

**Comment by ln2max** [comment]
Here we go, `install.sh` even warns:
```
Installed /usr/local/lib/python3.5/dist-packages/texttable-1.6.2-py3.5.egg
error: requests 2.12.4 is installed but requests<3,>=2.20.0 is required by {'docker-compose'}
```

**Comment by ln2max** [comment]
Debian's ancient package versions turned out to be the problem. Solution:
```
sudo apt remove python3-requests
sudo ./install.sh
```
