### ISSUE TITLE
Use of PosixPath in config.py breaks things that expect path as string

### ISSUE THREAD

**Issue by ln2max** [lncm/noma#68]
After fresh install on squeaky-clean Debian box:
```
$ sudo noma start
✅ Media directory exists
✅ Noma directory exists
✅ Compose directory exists
Traceback (most recent call last):
  File "/usr/local/bin/noma", line 11, in <module>
    load_entry_point('noma', 'console_scripts', 'noma')()
  File "/home/user/noma/noma/noma.py", line 83, in main
    node_fn(args)
  File "/home/user/noma/noma/noma.py", line 61, in node_fn
    node.start()
  File "/home/user/noma/noma/node.py", line 66, in start
    os.chdir(cfg.COMPOSE_MODE_PATH)
TypeError: argument should be string, bytes or integer, not PosixPath
```

**Comment by ln2max** [comment]
Issue comes from this line:
https://github.com/lncm/noma/blob/fc614713b24fb0a9afde328dae16d58f74fc0bae/noma/config.py#L29

**Comment by ln2max** [comment]
Here it is again:
```
$ sudo noma lnd create
Traceback (most recent call last):
  File "/usr/local/bin/noma", line 11, in <module>
    load_entry_point('noma', 'console_scripts', 'noma')()
  File "/home/user/noma/noma/noma.py", line 81, in main
    lnd_fn(args)
  File "/home/user/noma/noma/noma.py", line 35, in lnd_fn
    lnd.check_wallet()
  File "/home/user/noma/noma/lnd.py", line 24, in check_wallet
    create_wallet()
  File "/home/user/noma/noma/lnd.py", line 341, in create_wallet
    password_str = _wallet_password()
  File "/home/user/noma/noma/lnd.py", line 273, in _wallet_password
    if not path.exists(cfg.PASSWORD_FILE_PATH):
  File "/usr/lib/python3.5/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: argument should be string, bytes or integer, not PosixPath
```

**Comment by ln2max** [comment]
`test_lnd.py` also currently fails

**Comment by ln2max** [comment]
Should be resolved now
